### ISSUE TITLE
segfault when indexing several directories

### ISSUE THREAD

**Issue by asm0dey** [konstare/gdcv#1]
I'm trying to index several directories like this:

```
❯ ~/work_self/gdcv/gdcv -i En-En En-ru Ru-En
[1]    3636538 segmentation fault (core dumped)  ~/work_self/gdcv/gdcv -i En-En En-ru Ru-En
```

**Comment by konstare** [comment]
I am afraid I need some more information. This happens only if you index several directories? Does it work If you index each directory separately? Does it work if you index the parent directory?

**Comment by asm0dey** [comment]
Yes, only for >= 3 directories

**Comment by konstare** [comment]
I hope it works right now
