### ISSUE TITLE
Any support for EPWING dictionaries?

### ISSUE THREAD

**Issue by nanjigen** [konstare/gdcv#2]
I make extensive use of EPWING dictionaries in my translation work - I wonder what might be needed to support that format (as Goldendict itself already does).

Perhaps I could contribute something

**Comment by konstare** [comment]
>I wonder what might be needed to support that format

A lot of time.

The core of gdcv (just like GoldenDict) is the index file. Essentially, the index file shows where and how to look for the translation of a word(key). In this sense one can add support for any dictionary format without changing  the gut of the program. I remember that most of my time was consumed by the figuring out how the goldendict format works. Namely, how to read dictionary files, how to find the specific word in the file, how to format the search result.

I looked briefly into EPWING, and I could not find the English description of the format. In other words how the raw text is saved in EPWING. Goldendict uses libeb for reading such files, but i could not find the libeb API documentation either.
